#!/usr/bin/env python3
"""
validate.py - Validates all skill files (skill.md / SKILL.md) in the repo.

Usage:
    python scripts/validate.py           # validate and report
    python scripts/validate.py --fix     # also auto-fix "Generated by Gemini CLI" lines

Exit code 0 if all files pass, 1 if any fail.
"""

import argparse
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SKILL_FILENAMES = {"skill.md", "SKILL.md"}

FILLER_PHRASES = [
    "Apply the core logic",
    "Strive for flawless",
    "perfectly resolves",
]

LEGACY_TAG = "Generated by Gemini CLI"

MIN_LINES = 50
MAX_LINES = 200
MIN_DESCRIPTION_LEN = 50


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def parse_frontmatter(lines: list[str]) -> tuple[dict[str, str] | None, int]:
    """
    Parse YAML frontmatter delimited by '---'.

    Returns (fields_dict, body_start_line_index) or (None, 0) if not found.
    Only extracts simple key: value pairs (no nested YAML).
    """
    if not lines or lines[0].strip() != "---":
        return None, 0

    end = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break

    if end is None:
        return None, 0

    fields: dict[str, str] = {}
    for line in lines[1:end]:
        if ":" in line:
            key, _, value = line.partition(":")
            fields[key.strip()] = value.strip().strip('"').strip("'")

    return fields, end + 1


def validate_file(path: Path, fix: bool = False) -> tuple[bool, list[str]]:
    """
    Validate a single skill file.

    Returns (passed: bool, violations: list[str]).
    When fix=True, auto-removes "Generated by Gemini CLI" lines in-place.
    """
    violations: list[str] = []

    raw = path.read_text(encoding="utf-8", errors="replace")
    lines = raw.splitlines()

    # ------------------------------------------------------------------
    # Auto-fix: remove "Generated by Gemini CLI" lines
    # ------------------------------------------------------------------
    if fix:
        filtered = [ln for ln in lines if LEGACY_TAG not in ln]
        if len(filtered) != len(lines):
            path.write_text("\n".join(filtered) + "\n", encoding="utf-8")
            lines = filtered
            raw = "\n".join(lines)

    # ------------------------------------------------------------------
    # Rule 1: YAML frontmatter with name and description
    # ------------------------------------------------------------------
    fields, body_start = parse_frontmatter(lines)
    if fields is None:
        violations.append("Missing YAML frontmatter (--- delimited)")
    else:
        if "name" not in fields:
            violations.append("Frontmatter missing 'name' field")
        if "description" not in fields:
            violations.append("Frontmatter missing 'description' field")
        else:
            desc = fields["description"]
            if len(desc) < MIN_DESCRIPTION_LEN:
                violations.append(
                    f"'description' is {len(desc)} chars (minimum {MIN_DESCRIPTION_LEN})"
                )

    # Work on the full text for heading / block checks
    # ------------------------------------------------------------------
    # Rule 2-4: Headings
    # ------------------------------------------------------------------
    h1_lines = [ln for ln in lines if re.match(r"^#\s+\S", ln)]
    h2_lines = [ln for ln in lines if re.match(r"^##\s+\S", ln)]
    h3_lines = [ln for ln in lines if re.match(r"^###\s+\S", ln)]

    if not h1_lines:
        violations.append("No H1 heading (#) found")
    if not h2_lines:
        violations.append("No H2 section (##) found")
    if not h3_lines:
        violations.append("No H3 subsection (###) found")

    # ------------------------------------------------------------------
    # Rule 5: Line count
    # ------------------------------------------------------------------
    line_count = len(lines)
    if line_count < MIN_LINES:
        violations.append(
            f"File has {line_count} lines (minimum {MIN_LINES})"
        )
    elif line_count > MAX_LINES:
        violations.append(
            f"File has {line_count} lines (maximum {MAX_LINES})"
        )

    # ------------------------------------------------------------------
    # Rule 6: Code block
    # ------------------------------------------------------------------
    if "```" not in raw:
        violations.append("No code block (```) found")

    # ------------------------------------------------------------------
    # Rule 7: Edge case section
    # ------------------------------------------------------------------
    if not re.search(r"edge\s+case", raw, re.IGNORECASE):
        violations.append("No 'edge case' section found (case-insensitive)")

    # ------------------------------------------------------------------
    # Rule 8: Legacy tag
    # ------------------------------------------------------------------
    if LEGACY_TAG in raw:
        violations.append(f'Contains legacy tag: "{LEGACY_TAG}"')

    # ------------------------------------------------------------------
    # Rule 9: Generic filler phrases
    # ------------------------------------------------------------------
    for phrase in FILLER_PHRASES:
        if phrase in raw:
            violations.append(f'Contains generic filler phrase: "{phrase}"')

    passed = len(violations) == 0
    return passed, violations


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------

def find_skill_files(repo_root: Path) -> list[Path]:
    """Return all skill.md / SKILL.md files in immediate subdirectories."""
    skill_files: list[Path] = []
    for subdir in repo_root.iterdir():
        if not subdir.is_dir():
            continue
        for name in SKILL_FILENAMES:
            candidate = subdir / name
            if candidate.is_file():
                skill_files.append(candidate)
    return sorted(skill_files)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate skill.md / SKILL.md files in the repo."
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help='Auto-fix "Generated by Gemini CLI" lines by removing them.',
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent

    skill_files = find_skill_files(repo_root)
    if not skill_files:
        print("No skill files found.")
        return 0

    total = len(skill_files)
    passed_count = 0
    failed_count = 0
    all_violations: list[tuple[Path, list[str]]] = []

    # ------------------------------------------------------------------
    # Per-file output
    # ------------------------------------------------------------------
    print(f"Validating {total} skill file(s) in: {repo_root}\n")
    print("=" * 70)

    for path in skill_files:
        rel = path.relative_to(repo_root)
        passed, violations = validate_file(path, fix=args.fix)

        if passed:
            passed_count += 1
            print(f"PASS  {rel}")
        else:
            failed_count += 1
            all_violations.append((path, violations))
            print(f"FAIL  {rel}")
            for v in violations:
                print(f"        - {v}")

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print("=" * 70)
    print(f"\nSummary: {total} file(s) checked — {passed_count} passed, {failed_count} failed\n")

    if all_violations:
        print("All violations:")
        for path, violations in all_violations:
            rel = path.relative_to(repo_root)
            print(f"\n  {rel}")
            for v in violations:
                print(f"    - {v}")
        print()

    if args.fix and failed_count:
        print(
            'Note: --fix only removes "Generated by Gemini CLI" lines. '
            "Other violations must be fixed manually.\n"
        )

    return 0 if failed_count == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
